function [scenario, egoVehicle] = aula11_scenario_ex2()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.11 (R2021b) and Automated Driving Toolbox 3.4 (R2021b).
% Generated on: 13-Jan-2022 11:54:41

% Construct a drivingScenario object.
scenario = drivingScenario('StopTime', 10);

% Add all road segments
roadCenters = [0.2 0.9 0;
    42.5 -5.3 0;
    80.7 -18.4 0;
    112.7 -41.7 0;
    137.4 -75.1 0;
    149.8 -105 0;
    152.2 -142.8 0];
laneSpecification = lanespec(4);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [1.82 2.7 0.01], ...
    'Yaw', -9, ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [9.55 1.78 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [9.55 1.78 0.01;
    19.5 0.3 0;
    33 -1.4 0;
    43.4 -3.4 0;
    54.9 -6.5 0;
    65.5 -10.1 0;
    76.6 -14.9 0;
    86.3 -19.1 0;
    95.6 -25.1 0;
    105.1 -32.4 0;
    114.2 -40.4 0;
    121.3 -48.1 0;
    129.9 -58.8 0;
    136.3 -69.6 0;
    141.7 -79.8 0;
    146.1 -87.3 0;
    149.8 -97.9 0;
    153.2 -110.3 0;
    154.5 -121.8 0;
    154.9 -133.1 0;
    154.3 -141.3 0];
speed = [10;10;10;10;10;10;10;10;10;10;10;10;10;10;10;10;10;10;10;10;10];
trajectory(car1, waypoints, speed);

