function [scenario, egoVehicle] = aula11_scenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.11 (R2021b) and Automated Driving Toolbox 3.4 (R2021b).
% Generated on: 13-Jan-2022 11:43:54

% Construct a drivingScenario object.
scenario = drivingScenario('StopTime', 10);

% Add all road segments
roadCenters = [0.2 0.9 0;
    42.5 -5.3 0;
    80.7 -18.4 0;
    112.7 -41.7 0;
    137.4 -75.1 0;
    149.8 -105 0;
    152.2 -142.8 0];
laneSpecification = lanespec(4);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [1.82 2.7 0.01], ...
    'Yaw', -9, ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');

